const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');
dotenv.config();
const User = require('./models/User');
const Job = require('./models/Job');
const Company = require('./models/Company');
const Application = require('./models/Application');

mongoose.connect(process.env.MONGO_URI);

const importData = async () => {
  try {
    await User.deleteMany(); await Job.deleteMany(); await Company.deleteMany(); await Application.deleteMany();
    const hash = (p) => bcrypt.hashSync(p, 12);

    // ── Users ────────────────────────────────────────────────────────────────
    const users = await User.insertMany([
      // Admins
      { name:'Admin User',      email:'admin@jobportal.com',   password:hash('admin123'),   role:'admin',     headline:'Platform Administrator',           location:'Mumbai, IN',          skills:['Management','Strategy','Operations'] },

      // Employers
      { name:'Alice Johnson',   email:'alice@jobportal.com',   password:hash('alice123'),   role:'employer',  headline:'HR Manager at Tech Corp',           location:'New York, NY',        skills:['Recruiting','HR','Talent Acquisition'], about:'Passionate about finding top talent and building great teams at Tech Corp.', education:[{degree:'MBA in HR',institution:'NYU Stern',year:'2014'}], experience:[{title:'HR Manager',company:'Tech Corp',duration:'2018 – Present',current:true},{title:'HR Executive',company:'Deloitte',duration:'2014 – 2018',current:false}] },
      { name:'David Lee',       email:'david@jobportal.com',   password:hash('david123'),   role:'employer',  headline:'CTO at Innovate Ltd',               location:'Austin, TX',          skills:['Node.js','Python','AWS','System Design'], about:'Tech entrepreneur and CTO with 10+ years building cloud products.', education:[{degree:'B.Tech Computer Science',institution:'UT Austin',year:'2012'}], experience:[{title:'CTO',company:'Innovate Ltd',duration:'2018 – Present',current:true}] },
      { name:'Priya Sharma',    email:'priya@jobportal.com',   password:hash('priya123'),   role:'employer',  headline:'Founder & CEO at BrandBoost',       location:'Los Angeles, CA',     skills:['Marketing','Brand Strategy','Growth Hacking'], about:'Founded BrandBoost to help startups grow through digital marketing.', experience:[{title:'CEO',company:'BrandBoost',duration:'2021 – Present',current:true}] },
      { name:'James Carter',    email:'james@jobportal.com',   password:hash('james123'),   role:'employer',  headline:'VP Engineering at CloudNet',        location:'Seattle, WA',         skills:['AWS','Kubernetes','DevOps','Leadership'], experience:[{title:'VP Engineering',company:'CloudNet',duration:'2019 – Present',current:true}] },
      { name:'Sophia Kim',      email:'sophia@jobportal.com',  password:hash('sophia123'),  role:'employer',  headline:'Design Director at Design Studio',  location:'New York, NY',        skills:['UI/UX','Design Systems','Figma','Leadership'], experience:[{title:'Design Director',company:'Design Studio',duration:'2017 – Present',current:true}] },

      // Job Seekers
      { name:'Bob Smith',       email:'bob@jobportal.com',     password:hash('bob123'),     role:'jobseeker', headline:'Full Stack Developer',              location:'San Francisco, CA',   skills:['React','Node.js','MongoDB','TypeScript','GraphQL'], about:'Passionate full-stack developer with 4 years of experience building scalable web apps.', education:[{degree:'B.E. Computer Engineering',institution:'UC Berkeley',year:'2020'}], experience:[{title:'Software Engineer',company:'StartupXYZ',duration:'2020 – 2024',current:false}], certifications:[{name:'AWS Certified Developer',issuer:'Amazon',year:'2022'}] },
      { name:'Carol White',     email:'carol@jobportal.com',   password:hash('carol123'),   role:'jobseeker', headline:'UI/UX Designer',                    location:'Remote',              skills:['Figma','UI/UX','Adobe XD','Sketch','CSS'], about:'Creative designer who loves crafting pixel-perfect user experiences.', education:[{degree:'BFA Graphic Design',institution:'RISD',year:'2019'}], experience:[{title:'Product Designer',company:'CreativeAgency',duration:'2019 – 2023',current:false}] },
      { name:'Emma Brown',      email:'emma@jobportal.com',    password:hash('emma123'),    role:'jobseeker', headline:'Data Scientist',                    location:'Chicago, IL',         skills:['Python','ML','TensorFlow','SQL','Pandas'], about:'Data scientist with expertise in building predictive models for fintech.', education:[{degree:'M.S. Data Science',institution:'University of Chicago',year:'2021'}], certifications:[{name:'Google Data Analytics',issuer:'Google',year:'2022'}] },
      { name:'Arjun Mehta',     email:'arjun@jobportal.com',   password:hash('arjun123'),   role:'jobseeker', headline:'Backend Developer',                 location:'Pune, IN',            skills:['Java','Spring Boot','MySQL','Microservices','Docker'], about:'Backend engineer specializing in Java microservices and cloud deployments.', education:[{degree:'B.E. Information Technology',institution:'PICT Pune',year:'2021'}], experience:[{title:'Backend Developer',company:'Infosys',duration:'2021 – 2024',current:false}] },
      { name:'Lily Zhang',      email:'lily@jobportal.com',    password:hash('lily123'),    role:'jobseeker', headline:'Product Manager',                   location:'New York, NY',        skills:['Product Strategy','Agile','Jira','Analytics','Roadmapping'], about:'PM with 5 years of experience driving product growth in SaaS companies.', education:[{degree:'MBA',institution:'Columbia Business School',year:'2018'}], experience:[{title:'Senior PM',company:'SaaSCo',duration:'2018 – 2024',current:false}] },
      { name:'Marcus Johnson',  email:'marcus@jobportal.com',  password:hash('marcus123'),  role:'jobseeker', headline:'DevOps & Cloud Engineer',           location:'Austin, TX',          skills:['AWS','Terraform','Kubernetes','CI/CD','Linux'], about:'Cloud engineer with a passion for automation and infrastructure as code.', certifications:[{name:'AWS Solutions Architect',issuer:'Amazon',year:'2023'},{name:'CKA',issuer:'CNCF',year:'2023'}] },
      { name:'Nina Patel',      email:'nina@jobportal.com',    password:hash('nina123'),    role:'jobseeker', headline:'Digital Marketing Specialist',      location:'Mumbai, IN',          skills:['SEO','Google Ads','Content Marketing','Social Media','Analytics'], about:'Marketing specialist helping brands grow their online presence.', education:[{degree:'BMS Marketing',institution:'Mumbai University',year:'2020'}], experience:[{title:'Marketing Executive',company:'AdAgency',duration:'2020 – 2024',current:false}] },
      { name:'Tom Baker',       email:'tom@jobportal.com',     password:hash('tom123'),     role:'jobseeker', headline:'Mobile App Developer',              location:'Remote',              skills:['React Native','Flutter','iOS','Android','Firebase'], about:'Mobile developer with 6 published apps on App Store and Play Store.', experience:[{title:'Mobile Developer',company:'AppFactory',duration:'2019 – 2024',current:false}] },
      { name:'Zara Ahmed',      email:'zara@jobportal.com',    password:hash('zara123'),    role:'jobseeker', headline:'HR & Recruitment Specialist',       location:'Dubai, UAE',          skills:['Recruitment','HR Operations','LinkedIn','Onboarding','ATS'], about:'HR professional with experience in talent acquisition across MENA region.', education:[{degree:'B.A. Psychology',institution:'AUS',year:'2019'}] },
    ]);

    const [admin, alice, david, priya, james, sophia, bob, carol, emma, arjun, lily, marcus, nina, tom, zara] = users;

    // ── Jobs ─────────────────────────────────────────────────────────────────
    await Job.insertMany([

      // ── Tech Corp (alice) ─────────────────────────────────────────────────
      { title:'Senior Frontend Developer',    company:'Tech Corp', location:'New York, NY',     type:'Full Time',  salary:'$90k–$120k',  salaryMin:90000,  salaryMax:120000, category:'Technology', experienceLevel:'Senior Level', description:'Lead the frontend architecture for our flagship SaaS product used by 2M+ users. Work closely with product and design teams.', requirements:['5+ years React experience','TypeScript proficiency','Experience with design systems','Mentor junior devs'], responsibilities:['Architect scalable React components','Lead code reviews','Collaborate with UX designers','Improve core web vitals'], skills:['React','TypeScript','Tailwind CSS','GraphQL','Jest'], companyDesc:'Tech Corp is a leading software innovator trusted by enterprise clients globally.', postedBy:alice._id },

      { title:'Junior Frontend Developer',    company:'Tech Corp', location:'New York, NY',     type:'Full Time',  salary:'$55k–$75k',   salaryMin:55000,  salaryMax:75000,  category:'Technology', experienceLevel:'Entry Level',  description:'Join our growing frontend team and work on real features from day one. Great opportunity for fresh graduates.', requirements:['1+ year React experience','Understanding of HTML/CSS/JS','Willingness to learn'], responsibilities:['Build UI features from Figma designs','Fix bugs and write tests','Participate in sprint planning'], skills:['React','JavaScript','CSS','HTML','Git'], companyDesc:'Tech Corp is a leading software innovator.', postedBy:alice._id },

      { title:'Full Stack Engineer',          company:'Tech Corp', location:'Remote',           type:'Remote',     salary:'$85k–$110k',  salaryMin:85000,  salaryMax:110000, category:'Technology', experienceLevel:'Mid Level',    description:'Build end-to-end features for our cloud platform. Own features from design to deployment.', requirements:['3+ years full-stack experience','React + Node.js','REST API design'], responsibilities:['Build full features independently','Write backend APIs','Deploy to AWS'], skills:['React','Node.js','MongoDB','AWS','Docker'], companyDesc:'Tech Corp is a leading software innovator.', postedBy:alice._id },

      { title:'QA Engineer',                  company:'Tech Corp', location:'New York, NY',     type:'Full Time',  salary:'$60k–$80k',   salaryMin:60000,  salaryMax:80000,  category:'Technology', experienceLevel:'Mid Level',    description:'Ensure product quality through manual and automated testing across our product suite.', requirements:['Selenium or Cypress experience','Understanding of SDLC','Bug tracking tools'], responsibilities:['Write and run test cases','Automate regression tests','Report bugs clearly'], skills:['Cypress','Selenium','JIRA','Postman','SQL'], companyDesc:'Tech Corp is a leading software innovator.', postedBy:alice._id },

      // ── Innovate Ltd (david) ──────────────────────────────────────────────
      { title:'Backend Engineer',             company:'Innovate Ltd', location:'Austin, TX',    type:'Full Time',  salary:'$110k–$140k', salaryMin:110000, salaryMax:140000, category:'Technology', experienceLevel:'Mid Level',    description:'Design and build scalable APIs for our cloud-native platform. Work with a talented distributed team.', requirements:['3+ years Node.js experience','PostgreSQL / MongoDB','REST & GraphQL APIs'], responsibilities:['Build RESTful and GraphQL APIs','Design database schemas','Write unit and integration tests'], skills:['Node.js','PostgreSQL','GraphQL','Docker','Redis'], companyDesc:'Innovate Ltd builds next-gen cloud solutions.', postedBy:david._id },

      { title:'Senior Backend Engineer',      company:'Innovate Ltd', location:'Austin, TX',    type:'Full Time',  salary:'$130k–$160k', salaryMin:130000, salaryMax:160000, category:'Technology', experienceLevel:'Senior Level', description:'Own the backend architecture of our distributed microservices platform. Guide junior engineers.', requirements:['6+ years backend experience','Microservices architecture','Kafka or RabbitMQ knowledge'], responsibilities:['Design microservices architecture','Lead technical decisions','Conduct code reviews','Mentor engineers'], skills:['Node.js','Microservices','Kafka','Kubernetes','PostgreSQL'], companyDesc:'Innovate Ltd builds next-gen cloud solutions.', postedBy:david._id },

      { title:'Python Developer',             company:'Innovate Ltd', location:'Remote',        type:'Remote',     salary:'$90k–$120k',  salaryMin:90000,  salaryMax:120000, category:'Technology', experienceLevel:'Mid Level',    description:'Build internal automation tools and data pipelines using Python.', requirements:['3+ years Python','FastAPI or Django','Familiarity with data pipelines'], responsibilities:['Build Python microservices','Create internal automation tools','Work with data team'], skills:['Python','FastAPI','PostgreSQL','Celery','Docker'], companyDesc:'Innovate Ltd builds next-gen cloud solutions.', postedBy:david._id },

      { title:'Engineering Manager',          company:'Innovate Ltd', location:'Austin, TX',    type:'Full Time',  salary:'$150k–$180k', salaryMin:150000, salaryMax:180000, category:'Technology', experienceLevel:'Manager',      description:'Lead a team of 8 engineers building our core platform. Balance technical leadership with people management.', requirements:['5+ years engineering experience','2+ years management experience','Strong communication skills'], responsibilities:['Manage and grow a team of engineers','Run sprint planning and retrospectives','Partner with product to define roadmap'], skills:['Leadership','Agile','System Design','Hiring','Coaching'], companyDesc:'Innovate Ltd builds next-gen cloud solutions.', postedBy:david._id },

      // ── Design Studio (sophia) ────────────────────────────────────────────
      { title:'UI/UX Designer',               company:'Design Studio', location:'Remote',       type:'Remote',     salary:'$70k–$90k',   salaryMin:70000,  salaryMax:90000,  category:'Design', experienceLevel:'Mid Level',    description:'Design beautiful and functional user experiences for top global brands.', requirements:['Portfolio of UI/UX projects','Figma proficiency','Mobile-first design thinking'], responsibilities:['Create wireframes and high-fidelity prototypes','Conduct user research','Collaborate with dev team'], skills:['Figma','UI/UX','Adobe XD','User Research','Prototyping'], companyDesc:'Creative agency with global clients.', postedBy:sophia._id },

      { title:'Senior Product Designer',      company:'Design Studio', location:'New York, NY', type:'Full Time',  salary:'$95k–$115k',  salaryMin:95000,  salaryMax:115000, category:'Design', experienceLevel:'Senior Level', description:'Own the end-to-end design process for major client projects. Shape our design culture.', requirements:['6+ years product design','Strong portfolio','Experience with design systems'], responsibilities:['Lead design for key accounts','Build and maintain design systems','Present work to clients','Mentor junior designers'], skills:['Figma','Design Systems','Principle','User Testing','Sketch'], companyDesc:'Creative agency with global clients.', postedBy:sophia._id },

      { title:'Motion Graphics Designer',     company:'Design Studio', location:'Los Angeles, CA', type:'Full Time', salary:'$65k–$85k', salaryMin:65000,  salaryMax:85000,  category:'Design', experienceLevel:'Mid Level',    description:'Create stunning motion graphics and animations for digital campaigns.', requirements:['After Effects expertise','Portfolio of motion work','Understanding of brand guidelines'], responsibilities:['Produce motion graphics for social and web','Collaborate with creative directors','Deliver assets on deadline'], skills:['After Effects','Premiere Pro','Illustrator','Cinema 4D','Motion Design'], companyDesc:'Creative agency with global clients.', postedBy:sophia._id },

      { title:'Design Intern',                company:'Design Studio', location:'New York, NY', type:'Internship', salary:'$20k–$28k',   salaryMin:20000,  salaryMax:28000,  category:'Design', experienceLevel:'Entry Level',  description:'Learn from experienced designers on real client projects. 6-month internship with potential to convert to full-time.', requirements:['Enrolled in design program','Basic Figma knowledge','Passion for visual design'], responsibilities:['Support senior designers','Create social media assets','Prepare design specs'], skills:['Figma','Canva','Adobe Illustrator','Creativity'], companyDesc:'Creative agency with global clients.', postedBy:sophia._id },

      // ── CloudNet (james) ──────────────────────────────────────────────────
      { title:'DevOps Engineer',              company:'CloudNet', location:'Seattle, WA',      type:'Full Time',  salary:'$115k–$145k', salaryMin:115000, salaryMax:145000, category:'Technology', experienceLevel:'Senior Level', description:'Build and maintain cloud infrastructure and CI/CD pipelines for enterprise clients.', requirements:['AWS/GCP experience','Kubernetes expertise','Infrastructure as Code'], responsibilities:['Maintain CI/CD pipelines','Monitor and scale infrastructure','Automate deployments'], skills:['AWS','Kubernetes','Terraform','Docker','Python'], companyDesc:'CloudNet provides enterprise cloud infrastructure.', postedBy:james._id },

      { title:'Cloud Solutions Architect',    company:'CloudNet', location:'Seattle, WA',      type:'Full Time',  salary:'$140k–$170k', salaryMin:140000, salaryMax:170000, category:'Technology', experienceLevel:'Senior Level', description:'Design cloud architectures for enterprise clients migrating from on-prem to AWS/GCP.', requirements:['AWS SA Professional certification','5+ years cloud architecture','Client-facing experience'], responsibilities:['Design cloud migration plans','Present solutions to client CTOs','Ensure security compliance'], skills:['AWS','GCP','Azure','Solution Architecture','Security'], companyDesc:'CloudNet provides enterprise cloud infrastructure.', postedBy:james._id },

      { title:'Site Reliability Engineer',    company:'CloudNet', location:'Remote',           type:'Remote',     salary:'$120k–$150k', salaryMin:120000, salaryMax:150000, category:'Technology', experienceLevel:'Mid Level',    description:'Ensure 99.99% uptime for our clients critical cloud workloads through monitoring and automation.', requirements:['SRE or DevOps background','Prometheus / Grafana','Incident response experience'], responsibilities:['Define and monitor SLOs','Respond to incidents','Write runbooks','Automate toil'], skills:['Prometheus','Grafana','Kubernetes','Python','PagerDuty'], companyDesc:'CloudNet provides enterprise cloud infrastructure.', postedBy:james._id },

      { title:'Junior Cloud Engineer',        company:'CloudNet', location:'Seattle, WA',      type:'Full Time',  salary:'$70k–$90k',   salaryMin:70000,  salaryMax:90000,  category:'Technology', experienceLevel:'Entry Level',  description:'Kickstart your cloud career with hands-on AWS projects alongside senior engineers.', requirements:['AWS Cloud Practitioner a plus','Linux basics','Scripting knowledge'], responsibilities:['Support cloud infrastructure tasks','Monitor dashboards','Write automation scripts'], skills:['AWS','Linux','Python','Bash','Networking'], companyDesc:'CloudNet provides enterprise cloud infrastructure.', postedBy:james._id },

      // ── DataWorks (david) ─────────────────────────────────────────────────
      { title:'Data Analyst',                 company:'DataWorks', location:'Chicago, IL',     type:'Part Time',  salary:'$45k–$65k',   salaryMin:45000,  salaryMax:65000,  category:'Technology', experienceLevel:'Entry Level',  description:'Analyze business datasets and create dashboards that drive strategic decisions.', requirements:['SQL proficiency','Tableau or Power BI','Strong analytical mindset'], responsibilities:['Build interactive dashboards','Analyze sales and product data','Present findings to leadership'], skills:['SQL','Tableau','Python','Excel','Power BI'], companyDesc:'DataWorks turns raw data into actionable intelligence.', postedBy:david._id },

      { title:'Senior Data Scientist',        company:'DataWorks', location:'San Francisco, CA', type:'Full Time', salary:'$130k–$160k', salaryMin:130000, salaryMax:160000, category:'Technology', experienceLevel:'Senior Level', description:'Build and deploy ML models that directly impact client business outcomes.', requirements:['PhD or MS in CS/ML preferred','PyTorch / TensorFlow','Production ML systems experience'], responsibilities:['Train and evaluate ML models','Deploy models to production via MLOps','Write research reports'], skills:['Python','TensorFlow','PyTorch','MLOps','Feature Engineering'], companyDesc:'DataWorks turns raw data into actionable intelligence.', postedBy:david._id },

      { title:'Data Engineer',                company:'DataWorks', location:'Chicago, IL',     type:'Full Time',  salary:'$95k–$120k',  salaryMin:95000,  salaryMax:120000, category:'Technology', experienceLevel:'Mid Level',    description:'Build and maintain data pipelines that power our analytics platform.', requirements:['Apache Spark or Airflow','Python / Scala','Data warehouse experience'], responsibilities:['Design and build ETL pipelines','Optimize data warehouse queries','Ensure data quality'], skills:['Apache Spark','Airflow','Python','Snowflake','DBT'], companyDesc:'DataWorks turns raw data into actionable intelligence.', postedBy:david._id },

      { title:'Business Intelligence Analyst', company:'DataWorks', location:'Remote',         type:'Remote',     salary:'$70k–$90k',   salaryMin:70000,  salaryMax:90000,  category:'Technology', experienceLevel:'Mid Level',    description:'Transform complex datasets into clear visualizations and business insights for clients.', requirements:['Tableau / Looker expertise','SQL intermediate level','Strong communication skills'], responsibilities:['Create client-facing dashboards','Write SQL reports','Present insights in weekly reviews'], skills:['Tableau','SQL','Looker','Google Sheets','Storytelling'], companyDesc:'DataWorks turns raw data into actionable intelligence.', postedBy:david._id },

      // ── BrandBoost (priya) ────────────────────────────────────────────────
      { title:'Digital Marketing Manager',    company:'BrandBoost', location:'Los Angeles, CA', type:'Full Time', salary:'$65k–$85k',   salaryMin:65000,  salaryMax:85000,  category:'Marketing', experienceLevel:'Mid Level',    description:'Lead digital marketing campaigns for a portfolio of D2C brands.', requirements:['3+ years digital marketing','Google Ads & Meta Ads proficiency','Analytics mindset'], responsibilities:['Plan and execute paid campaigns','Manage social media calendars','Track and report ROAS'], skills:['Google Ads','Meta Ads','SEO','Content Marketing','Analytics'], companyDesc:'BrandBoost is a digital marketing agency specializing in growth.', postedBy:priya._id },

      { title:'SEO Specialist',               company:'BrandBoost', location:'Remote',         type:'Remote',     salary:'$50k–$70k',   salaryMin:50000,  salaryMax:70000,  category:'Marketing', experienceLevel:'Mid Level',    description:'Drive organic growth for our clients through technical and content SEO strategies.', requirements:['3+ years SEO experience','Ahrefs / SEMrush expertise','Technical SEO knowledge'], responsibilities:['Conduct keyword research','Optimize on-page and technical SEO','Build backlinks','Report rankings'], skills:['SEO','Ahrefs','SEMrush','Google Search Console','Content Writing'], companyDesc:'BrandBoost is a digital marketing agency specializing in growth.', postedBy:priya._id },

      { title:'Social Media Manager',         company:'BrandBoost', location:'Los Angeles, CA', type:'Full Time', salary:'$45k–$60k',   salaryMin:45000,  salaryMax:60000,  category:'Marketing', experienceLevel:'Entry Level',  description:'Manage social media presence for 5+ client brands across Instagram, TikTok, LinkedIn.', requirements:['1+ year social media experience','Strong copywriting skills','Eye for visual content'], responsibilities:['Create and schedule posts','Engage with followers','Run influencer campaigns','Analyse performance'], skills:['Instagram','TikTok','LinkedIn','Canva','Copywriting'], companyDesc:'BrandBoost is a digital marketing agency specializing in growth.', postedBy:priya._id },

      { title:'Marketing Intern',             company:'BrandBoost', location:'Los Angeles, CA', type:'Internship', salary:'$20k–$28k',  salaryMin:20000,  salaryMax:28000,  category:'Marketing', experienceLevel:'Entry Level',  description:'Gain hands-on marketing experience working across SEO, paid ads, and social media.', requirements:['Marketing or Communications student','Eagerness to learn','Basic Canva / writing skills'], responsibilities:['Assist campaign execution','Write blog posts and captions','Research competitors'], skills:['Social Media','Content Writing','Canva','SEO Basics'], companyDesc:'BrandBoost is a digital marketing agency specializing in growth.', postedBy:priya._id },

      { title:'Content Strategist',           company:'BrandBoost', location:'Remote',         type:'Remote',     salary:'$55k–$75k',   salaryMin:55000,  salaryMax:75000,  category:'Marketing', experienceLevel:'Mid Level',    description:'Develop content strategies that drive traffic, engagement, and conversions for client brands.', requirements:['Portfolio of content work','SEO writing skills','Understanding of buyer journeys'], responsibilities:['Create editorial calendars','Write long-form content','Brief freelance writers','Measure content performance'], skills:['Content Strategy','SEO','Copywriting','WordPress','Analytics'], companyDesc:'BrandBoost is a digital marketing agency specializing in growth.', postedBy:priya._id },

      // ── ProductHub (david) ────────────────────────────────────────────────
      { title:'Product Manager',              company:'ProductHub', location:'Austin, TX',     type:'Full Time',  salary:'$100k–$130k', salaryMin:100000, salaryMax:130000, category:'Operations', experienceLevel:'Senior Level', description:'Drive product strategy and roadmap for our SaaS platform serving 50k+ SMBs.', requirements:['5+ years PM experience','Technical background preferred','Data-driven mindset'], responsibilities:['Define product roadmap','Partner with engineering and design','Analyse product metrics','Run user interviews'], skills:['Product Strategy','Agile','Analytics','Jira','Roadmapping'], companyDesc:'ProductHub is a fast-growing SaaS startup focused on product excellence.', postedBy:david._id },

      { title:'Associate Product Manager',    company:'ProductHub', location:'Austin, TX',     type:'Full Time',  salary:'$70k–$90k',   salaryMin:70000,  salaryMax:90000,  category:'Operations', experienceLevel:'Entry Level',  description:'Learn the craft of product management by owning small features and experiments on our platform.', requirements:['1+ year product or engineering experience','Curiosity and analytical thinking','Familiarity with Agile'], responsibilities:['Write product specs','Coordinate between design and engineering','Analyse A/B test results'], skills:['Product Management','SQL','Figma','Agile','User Research'], companyDesc:'ProductHub is a fast-growing SaaS startup.', postedBy:david._id },

      { title:'Customer Success Manager',     company:'ProductHub', location:'Remote',         type:'Remote',     salary:'$60k–$80k',   salaryMin:60000,  salaryMax:80000,  category:'Sales', experienceLevel:'Mid Level',    description:'Own the relationship with our SMB customers and drive retention and expansion revenue.', requirements:['2+ years customer success','SaaS product experience','Excellent communication'], responsibilities:['Onboard new customers','Run QBRs','Identify upsell opportunities','Track churn signals'], skills:['Customer Success','CRM','Salesforce','Communication','Data Analysis'], companyDesc:'ProductHub is a fast-growing SaaS startup.', postedBy:david._id },

      // ── Supportify (alice) ────────────────────────────────────────────────
      { title:'Customer Support Specialist',  company:'Supportify', location:'Remote',         type:'Part Time',  salary:'$28k–$38k',   salaryMin:28000,  salaryMax:38000,  category:'Operations', experienceLevel:'Entry Level',  description:'Help customers via live chat and email with empathy and speed.', requirements:['Excellent written communication','Patient and empathetic','Problem-solving skills'], responsibilities:['Handle customer queries','Resolve product issues','Escalate complex bugs','Document solutions'], skills:['Customer Service','Zendesk','Communication','CRM','Typing'], companyDesc:'Supportify provides 24/7 customer support solutions at scale.', postedBy:alice._id },

      { title:'Support Team Lead',            company:'Supportify', location:'Remote',         type:'Full Time',  salary:'$50k–$65k',   salaryMin:50000,  salaryMax:65000,  category:'Operations', experienceLevel:'Mid Level',    description:'Lead a team of 10 support agents and drive CSAT and resolution metrics.', requirements:['2+ years in customer support','Team leadership experience','Data-driven approach to support'], responsibilities:['Coach support agents','Monitor team KPIs','Handle escalations','Improve support processes'], skills:['Leadership','Zendesk','CSAT','Coaching','Process Improvement'], companyDesc:'Supportify provides 24/7 customer support solutions at scale.', postedBy:alice._id },

      { title:'Technical Support Engineer',   company:'Supportify', location:'Remote',         type:'Full Time',  salary:'$55k–$70k',   salaryMin:55000,  salaryMax:70000,  category:'Technology', experienceLevel:'Mid Level',    description:'Provide technical support to our enterprise clients and liaise with engineering on bug fixes.', requirements:['Technical background (CS or equivalent)','REST API understanding','Strong problem solving'], responsibilities:['Diagnose technical issues','Reproduce bugs for engineering','Write technical documentation'], skills:['Technical Support','REST APIs','SQL','JIRA','Documentation'], companyDesc:'Supportify provides 24/7 customer support solutions at scale.', postedBy:alice._id },

      // ── MobileFirst (alice) ───────────────────────────────────────────────
      { title:'React Native Developer',       company:'MobileFirst', location:'Remote',        type:'Remote',     salary:'$80k–$110k',  salaryMin:80000,  salaryMax:110000, category:'Technology', experienceLevel:'Mid Level',    description:'Build high-performance cross-platform apps for iOS and Android using React Native.', requirements:['3+ years React Native','Published app(s) on App Store or Play Store','REST API integration'], responsibilities:['Build new app features','Optimise app performance','Write unit tests','Work closely with design'], skills:['React Native','JavaScript','iOS','Android','Firebase'], companyDesc:'MobileFirst specialises in mobile-first experiences.', postedBy:alice._id },

      { title:'Flutter Developer',            company:'MobileFirst', location:'Remote',        type:'Remote',     salary:'$85k–$115k',  salaryMin:85000,  salaryMax:115000, category:'Technology', experienceLevel:'Mid Level',    description:'Build beautiful cross-platform mobile apps with Flutter for our growing client portfolio.', requirements:['2+ years Flutter / Dart','App Store / Play Store deployment experience','Bloc or Riverpod state management'], responsibilities:['Build Flutter apps from scratch','Integrate APIs and Firebase','Work with designers on pixel-perfect UI'], skills:['Flutter','Dart','Firebase','Bloc','Android','iOS'], companyDesc:'MobileFirst specialises in mobile-first experiences.', postedBy:alice._id },

      { title:'iOS Developer',                company:'MobileFirst', location:'Remote',        type:'Remote',     salary:'$90k–$120k',  salaryMin:90000,  salaryMax:120000, category:'Technology', experienceLevel:'Mid Level',    description:'Build native iOS apps using Swift for clients in fintech, health, and e-commerce.', requirements:['3+ years Swift','UIKit and SwiftUI knowledge','App Store submission experience'], responsibilities:['Develop native iOS features','Implement push notifications and payments','Submit and manage App Store releases'], skills:['Swift','SwiftUI','UIKit','Xcode','CocoaPods'], companyDesc:'MobileFirst specialises in mobile-first experiences.', postedBy:alice._id },

      // ── HR roles across companies ─────────────────────────────────────────
      { title:'HR Generalist',                company:'Tech Corp', location:'New York, NY',    type:'Full Time',  salary:'$55k–$72k',   salaryMin:55000,  salaryMax:72000,  category:'HR', experienceLevel:'Mid Level',    description:'Support end-to-end HR operations including recruitment, onboarding, and employee relations.', requirements:['2+ years HR experience','HRMS tools knowledge','Strong interpersonal skills'], responsibilities:['Manage recruitment pipelines','Coordinate onboarding','Handle employee queries','Maintain HR records'], skills:['Recruitment','HRMS','Onboarding','Employee Relations','MS Office'], companyDesc:'Tech Corp is a leading software innovator.', postedBy:alice._id },

      { title:'Talent Acquisition Specialist', company:'CloudNet', location:'Seattle, WA',     type:'Full Time',  salary:'$60k–$80k',   salaryMin:60000,  salaryMax:80000,  category:'HR', experienceLevel:'Mid Level',    description:'Source and recruit top engineering talent for our fast-growing cloud team.', requirements:['2+ years tech recruiting','LinkedIn Recruiter experience','Strong pipeline management'], responsibilities:['Source candidates via LinkedIn and GitHub','Conduct screening calls','Manage ATS pipeline','Partner with hiring managers'], skills:['Sourcing','LinkedIn Recruiter','Interviewing','ATS','Negotiation'], companyDesc:'CloudNet provides enterprise cloud infrastructure.', postedBy:james._id },

      // ── Finance role ──────────────────────────────────────────────────────
      { title:'Financial Analyst',            company:'ProductHub', location:'Austin, TX',     type:'Full Time',  salary:'$70k–$90k',   salaryMin:70000,  salaryMax:90000,  category:'Finance', experienceLevel:'Mid Level',    description:'Support financial planning and analysis for a high-growth SaaS company.', requirements:['CFA Part 1 or equivalent','Excel and financial modelling','SaaS metrics understanding'], responsibilities:['Build financial models','Prepare monthly P&L reports','Support fundraising with data','Forecast ARR and churn'], skills:['Financial Modelling','Excel','SaaS Metrics','SQL','PowerPoint'], companyDesc:'ProductHub is a fast-growing SaaS startup.', postedBy:david._id },

    ]);

    // ── Companies ─────────────────────────────────────────────────────────────
    await Company.insertMany([
      { name:'Tech Corp',     founded:'2015', employees:'250+', website:'https://techcorp.io',       industry:'Software',   headquarters:'New York, NY',     tagline:'Innovation at scale',       benefits:['Health Insurance','Remote Friendly','401k Match','Gym Membership','Stock Options'], about:'Tech Corp builds world-class software products used by millions of enterprise customers globally. We believe great software changes lives.' },
      { name:'Innovate Ltd',  founded:'2018', employees:'120',  website:'https://innovateltd.com',   industry:'Cloud',      headquarters:'Austin, TX',        tagline:'Building the future',       benefits:['Stock Options','Flexible Hours','Home Office Stipend','Unlimited PTO'], about:'We build next-generation cloud-native solutions that help companies scale without limits.' },
      { name:'Design Studio', founded:'2012', employees:'80',   website:'https://designstudio.co',   industry:'Design',     headquarters:'New York, NY',      tagline:'Design that inspires',      benefits:['Creative Fridays','Workshops','Paid Time Off','Annual Retreat'], about:'Creative agency serving global brands from startups to Fortune 500. We craft design that connects.' },
      { name:'ProductHub',    founded:'2020', employees:'60',   website:'https://producthub.io',     industry:'SaaS',       headquarters:'Austin, TX',        tagline:'Product-led growth',        benefits:['Early Fridays','Health & Wellness','Learning Budget','Equity'], about:'Fast-growing SaaS startup helping 50,000+ SMBs manage their products better.' },
      { name:'CloudNet',      founded:'2016', employees:'400',  website:'https://cloudnet.com',      industry:'Cloud',      headquarters:'Seattle, WA',       tagline:'Powering the cloud',        benefits:['Global Team','Certification Reimbursement','Home Internet','Health Insurance'], about:'Enterprise cloud infrastructure trusted by Fortune 500 companies. We keep the world connected.' },
      { name:'DataWorks',     founded:'2019', employees:'45',   website:'https://dataworks.tech',    industry:'Data & AI',  headquarters:'Chicago, IL',       tagline:'Insights driven',           benefits:['Data Camp Subscription','Flexible Location','Equity','Learning Budget'], about:'We turn raw data into actionable business intelligence that drives real decisions.' },
      { name:'BrandBoost',    founded:'2021', employees:'25',   website:'https://brandboost.agency', industry:'Marketing',  headquarters:'Los Angeles, CA',   tagline:'Amplify your brand',        benefits:['Social Events','Mentorship','Creative Tools','Flexible Hours'], about:'Digital marketing agency helping startups and D2C brands grow through data-driven campaigns.' },
      { name:'Supportify',    founded:'2017', employees:'150',  website:'https://supportify.io',     industry:'CX & Support',headquarters:'Remote',            tagline:'Support that scales',       benefits:['100% Remote','Wellness Days','Coaching','Home Office Budget'], about:'We provide 24/7 customer support solutions for SaaS companies at any scale.' },
      { name:'MobileFirst',   founded:'2022', employees:'30',   website:'https://mobilefirst.dev',   industry:'Mobile',     headquarters:'Remote',            tagline:'Mobile-first, always',      benefits:['Remote First','Flexible Hours','Equipment Budget','Annual Offsite'], about:'We build beautiful, performant mobile apps that users love — on iOS, Android, and everything in between.' },
    ]);

    console.log('✅ Data imported successfully!');
    console.log('');
    console.log('👥 User accounts:');
    console.log('  Admin    : admin@jobportal.com  / admin123');
    console.log('  Employer : alice@jobportal.com  / alice123');
    console.log('  Employer : david@jobportal.com  / david123');
    console.log('  Employer : priya@jobportal.com  / priya123');
    console.log('  Employer : james@jobportal.com  / james123');
    console.log('  Employer : sophia@jobportal.com / sophia123');
    console.log('  Jobseeker: bob@jobportal.com    / bob123');
    console.log('  Jobseeker: carol@jobportal.com  / carol123');
    console.log('  Jobseeker: emma@jobportal.com   / emma123');
    console.log('  Jobseeker: arjun@jobportal.com  / arjun123');
    console.log('  Jobseeker: lily@jobportal.com   / lily123');
    console.log('  Jobseeker: marcus@jobportal.com / marcus123');
    console.log('  Jobseeker: nina@jobportal.com   / nina123');
    console.log('  Jobseeker: tom@jobportal.com    / tom123');
    console.log('  Jobseeker: zara@jobportal.com   / zara123');
    console.log('');
    console.log('📊 Summary:');
    console.log('  15 users · 40 jobs · 9 companies');
    process.exit();
  } catch (e) { console.error(e); process.exit(1); }
};

const destroyData = async () => {
  try {
    await User.deleteMany(); await Job.deleteMany(); await Company.deleteMany(); await Application.deleteMany();
    console.log('🗑️  Data destroyed');
    process.exit();
  } catch (e) { console.error(e); process.exit(1); }
};

if (process.argv[2] === '-d') destroyData(); else importData();
